// <auto-generated />
using JuanDavidB.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JuanDavidB.Persistence.Migrations
{
    [DbContext(typeof(JuanDavidBContext))]
    [Migration("20221001162837_ChangeLenghtPais")]
    partial class ChangeLenghtPais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JuanDavidB.Domain.Tablero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arranque")
                        .HasColumnType("int");

                    b.Property<string>("Deportista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Envion")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("TotalPeso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tableros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arranque = 134,
                            Deportista = "Carlos Alviz",
                            Envion = 177,
                            Pais = "AUS",
                            TotalPeso = 311
                        },
                        new
                        {
                            Id = 2,
                            Arranque = 130,
                            Deportista = "Andrés Sabogal",
                            Envion = 180,
                            Pais = "CHN",
                            TotalPeso = 310
                        },
                        new
                        {
                            Id = 3,
                            Arranque = 125,
                            Deportista = "Jorge Ortega",
                            Envion = 184,
                            Pais = "FRA",
                            TotalPeso = 309
                        },
                        new
                        {
                            Id = 4,
                            Arranque = 0,
                            Deportista = "Pablo Velasco",
                            Envion = 150,
                            Pais = "AUS",
                            TotalPeso = 150
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
